version: '7.17'
services:
  elasticsearch:
    image: elasticsearch:7.17.19
    container_name: elasticsearch-grafana
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  logstash:
    # image: logstash:7.17.19
    image: logstash:8.12.2
    container_name: logstash-grafana
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs:/usr/share/logstash/logs
    # ports:
    #   - 8090:5000
    ports:
      - 5044:5044
    depends_on:
      - elasticsearch

  # grafana:
  #   image: grafana/grafana:10.4.2
  #   container_name: grafana
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - elasticsearch
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin

  # setup:
  #   image: alpine:3.19.1
  #   container_name: setup-grafana
  #   depends_on:
  #     - elasticsearch
  #   volumes:
  #     - ./setup.sh:/setup.sh
  #   entrypoint: /bin/sh /setup.sh

volumes:
  esdata:
    driver: local

