version: '7.17'
services:
  elasticsearch:
    image: elasticsearch:7.17.19
    container_name: elasticsearch-grafana
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  logstash:
    image: logstash:8.12.2
    container_name: logstash-grafana
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./output_files:/usr/share/logstash/output_files
    ports:
      - 5044:5044
    depends_on:
      - elasticsearch
      # - json_processor

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - elasticsearch
      - logstash
      # - json_processor
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  # json_processor:
  #   image: python:3.9-slim
  #   container_name: json_processor
  #   volumes:
  #     - ./process_json.py:/app/process_json.py
  #     - ./input.json:/app/input.json
  #     - ./output_files:/app/output_files
  #   working_dir: /app
  #   command: ["python", "process_json.py"]
  #   depends_on:
  #     - elasticsearch

volumes:
  esdata:
    driver: local