version: '7.17'
services:
  json_processor:
    image: python:3.9-slim
    container_name: json_processor-vnet
    volumes:
      - ./process_json.py:/app/process_json.py
      - ./logs/:/app/logs
      - ./output_files:/app/output_files
    working_dir: /app
    command: ["python", "process_json.py"]

  elasticsearch:
    image: elasticsearch:7.17.19
    container_name: elasticsearch-vnet
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    depends_on:
      - json_processor

  kibana:
    image: kibana:7.17.19
    container_name: kibana-vnet
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
      - json_processor

  logstash:
    image: logstash:8.12.2
    container_name: logstash-vnet
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./output_files:/usr/share/logstash/output_files
    ports:
      - 5044:5044
    depends_on:
      - setup

  setup:
    image: alpine:3.19.1
    container_name: setup_kibana-vnet
    depends_on:
      - kibana
    volumes:
      - ./setup.sh:/setup.sh
    entrypoint: /bin/sh /setup.sh

volumes:
  esdata:
    driver: local

